# Case Four- Selected food Prices Watch in Nigeria

### Analysis on different food prices and comparison of different food items to make informed predictions about the future.

In [37]:
import pandas as pd

In [65]:
ng=pd.read_csv("cfafrica-_-data-team-_-wanadata-_-nigeria-_-food-prices-_-april-2020-national.csv")

#reading top 5 rows
ng.head(5)

,ItemLabels,Jan-17,Feb-17,Mar-17,Apr-17,May-17,Jun-17,Jul-17,Aug-17,Sep-17,...,Nov-19,Dec-19,Jan-20,Feb-20,Mar-20,Apr-20,YoY April,MoM,Lowest,Highest
0,Bread sliced 500g,302.87,299.75,297.51,296.63,307.70,320.58,314.47,304.20,310.62,...,299.59,304.06,302.45,303.06,304.60,316.55,6.27,3.92,Bauchi (238.57),Bayelsa (446.15)
1,"Gari white,sold loose",219.56,260.94,273.67,288.45,292.97,315.61,317.10,310.15,301.99,...,160.06,159.39,159.64,159.33,164.60,190.23,16.44,15.57,Ekiti (126.84),Bayelsa (325.48)
2,"Gari yellow,sold loose",255.83,250.45,302.05,320.92,326.83,354.55,350.46,345.82,335.94,...,181.32,183.26,182.19,186.35,192.41,211.83,16.02,10.09,Benue (146.57),Bayelsa (345.48)
3,Rice Medium Grained,312.08,352.69,377.99,332.81,350.36,348.23,344.40,313.45,339.47,...,378.50,381.68,381.42,373.16,368.36,394.56,24.74,7.11,Kogi (255),Bayelsa (580)
4,"Rice,imported high quality sold loose",402.01,410.58,418.71,388.46,410.55,415.84,409.20,384.35,398.01,...,445.45,459.90,453.24,444.04,438.66,471.84,31.97,7.56,Sokoto (353.33),Bayelsa (659.64)

In [66]:
#lists all columns in our data
ng.columns

Index(['ItemLabels', 'Jan-17', 'Feb-17', 'Mar-17', 'Apr-17', 'May-17',
       'Jun-17', 'Jul-17', 'Aug-17', 'Sep-17', 'Oct-17', 'Nov-17', 'Dec-17',
       'Jan-18', 'Feb-18', 'Mar-18', 'Apr-18', 'May-18', 'Jun-18', 'Jul-18',
       'Aug-18', 'Sep-18', 'Oct-18', 'Nov-18', 'Dec-18', 'Jan-19', 'Feb-19',
       'Mar-19', 'Apr-19', 'May-19', 'Jun-19', 'Jul-19', 'Aug-19', 'Sep-19',
       'Oct-19', 'Nov-19', 'Dec-19', 'Jan-20', 'Feb-20', 'Mar-20', 'Apr-20',
       'YoY April', 'MoM', 'Lowest', 'Highest'],
      dtype='object')

In [67]:
#read through each column 
for index, row in ng.iterrows():
    print(index,row)

0 ItemLabels    Bread sliced 500g
Jan-17                   302.87
Feb-17                   299.75
Mar-17                   297.51
Apr-17                   296.63
May-17                    307.7
Jun-17                   320.58
Jul-17                   314.47
Aug-17                    304.2
Sep-17                   310.62
Oct-17                   305.88
Nov-17                   298.96
Dec-17                   290.05
Jan-18                   313.43
Feb-18                   314.17
Mar-18                   305.88
Apr-18                   306.54
May-18                   305.98
Jun-18                      308
Jul-18                   305.25
Aug-18                   307.97
Sep-18                   303.84
Oct-18                   299.19
Nov-18                   305.48
Dec-18                   296.91
Jan-19                   300.61
Feb-19                   299.11
Mar-19                   299.98
Apr-19                   297.87
May-19                   297.28
Jun-19                   292.73
Jul-19                   293.49
Aug-19                   301.36
Sep-19                   302.59
Oct-19                   296.56
Nov-19                   299.59
Dec-19                   304.06
Jan-20                   302.45
Feb-20                   303.06
Mar-20                    304.6
Apr-20                   316.55
YoY April                  6.27
MoM                        3.92
Lowest          Bauchi (238.57)
Highest        Bayelsa (446.15)
Name: 0, dtype: object
1 ItemLabels    Gari white,sold loose
Jan-17                       219.56
Feb-17                       260.94
Mar-17                       273.67
Apr-17                       288.45
May-17                       292.97
Jun-17                       315.61
Jul-17                        317.1
Aug-17                       310.15
Sep-17                       301.99
Oct-17                        268.1
Nov-17                       251.91
Dec-17                       199.68
Jan-18                       229.26
Feb-18                       210.21
Mar-18                       209.12
Apr-18                       208.21
May-18                       216.01
Jun-18                       216.72
Jul-18                       200.67
Aug-18                       198.82
Sep-18                       195.86
Oct-18                       188.39
Nov-18                       183.59
Dec-18                       166.64
Jan-19                        165.8
Feb-19                       166.61
Mar-19                       163.51
Apr-19                       163.37
May-19                       161.55
Jun-19                       145.31
Jul-19                       151.73
Aug-19                        154.1
Sep-19                       154.55
Oct-19                       162.42
Nov-19                       160.06
Dec-19                       159.39
Jan-20                       159.64
Feb-20                       159.33
Mar-20                        164.6
Apr-20                       190.23
YoY April                     16.44
MoM                           15.57
Lowest               Ekiti (126.84)
Highest            Bayelsa (325.48)
Name: 1, dtype: object
2 ItemLabels    Gari yellow,sold loose
Jan-17                        255.83
Feb-17                        250.45
Mar-17                        302.05
Apr-17                        320.92
May-17                        326.83
Jun-17                        354.55
Jul-17                        350.46
Aug-17                        345.82
Sep-17                        335.94
Oct-17                        305.02
Nov-17                        289.15
Dec-17                        219.75
Jan-18                        271.35
Feb-18                        250.06
Mar-18                        243.99
Apr-18                         246.5
May-18                        256.51
Jun-18                        259.83
Jul-18                        248.72
Aug-18                        246.75
Sep-18                         253.7
Oct-18                        236.26
Nov-18                        222.42
Dec-18                        195.99
Jan-19                        191.78
Feb-19                        191.06
Mar-19                        184.18
Apr-19                        182.59
May-19                        180.75
Jun-19                        156.02
Jul-19                        154.05
Aug-19                        167.34
Sep-19                        172.23
Oct-19                        175.57
Nov-19                        181.32
Dec-19                        183.26
Jan-20                        182.19
Feb-20                        186.35
Mar-20                        192.41
Apr-20                        211.83
YoY April                      16.02
MoM                            10.09
Lowest                Benue (146.57)
Highest             Bayelsa (345.48)
Name: 2, dtype: object
3 ItemLabels    Rice Medium Grained
Jan-17                     312.08
Feb-17                     352.69
Mar-17                     377.99
Apr-17                     332.81
May-17                     350.36
Jun-17                     348.23
Jul-17                      344.4
Aug-17                     313.45
Sep-17                     339.47
Oct-17                     320.64
Nov-17                     309.87
Dec-17                      304.9
Jan-18                     308.53
Feb-18                     314.77
Mar-18                     317.17
Apr-18                     323.56
May-18                     325.37
Jun-18                     323.12
Jul-18                     319.35
Aug-18                     322.55
Sep-18                     319.46
Oct-18                     314.89
Nov-18                     318.94
Dec-18                        318
Jan-19                     317.63
Feb-19                     314.53
Mar-19                     313.55
Apr-19                      316.3
May-19                     316.94
Jun-19                     308.07
Jul-19                     305.93
Aug-19                     309.27
Sep-19                      326.4
Oct-19                     339.78
Nov-19                      378.5
Dec-19                     381.68
Jan-20                     381.42
Feb-20                     373.16
Mar-20                     368.36
Apr-20                     394.56
YoY April                   24.74
MoM                          7.11
Lowest                 Kogi (255)
Highest             Bayelsa (580)
Name: 3, dtype: object
4 ItemLabels    Rice,imported high quality sold loose
Jan-17                                       402.01
Feb-17                                       410.58
Mar-17                                       418.71
Apr-17                                       388.46
May-17                                       410.55
Jun-17                                       415.84
Jul-17                                        409.2
Aug-17                                       384.35
Sep-17                                       398.01
Oct-17                                        368.9
Nov-17                                       360.83
Dec-17                                       371.21
Jan-18                                       360.76
Feb-18                                       365.21
Mar-18                                       363.33
Apr-18                                       369.35
May-18                                       374.63
Jun-18                                       373.47
Jul-18                                       370.79
Aug-18                                       375.02
Sep-18                                       371.32
Oct-18                                       373.04
Nov-18                                       376.63
Dec-18                                       370.57
Jan-19                                       366.04
Feb-19                                       364.39
Mar-19                                        361.9
Apr-19                                       357.55
May-19                                       361.39
Jun-19                                       352.83
Jul-19                                        356.1
Aug-19                                       356.61
Sep-19                                       371.13
Oct-19                                       382.57
Nov-19                                       445.45
Dec-19                                        459.9
Jan-20                                       453.24
Feb-20                                       444.04
Mar-20                                       438.66
Apr-20                                       471.84
YoY April                                     31.97
MoM                                            7.56
Lowest                              Sokoto (353.33)
Highest                            Bayelsa (659.64)
Name: 4, dtype: object
5 ItemLabels              Tomato
Jan-17                  247.55
Feb-17                  236.62
Mar-17                  268.64
Apr-17                  285.72
May-17                  339.72
Jun-17                     375
Jul-17                  394.13
Aug-17                   431.3
Sep-17                  322.39
Oct-17                  291.53
Nov-17                  286.39
Dec-17                  276.18
Jan-18                  271.99
Feb-18                   267.1
Mar-18                  267.09
Apr-18                  289.49
May-18                  307.14
Jun-18                  317.67
Jul-18                  336.29
Aug-18                  336.65
Sep-18                  328.26
Oct-18                  306.59
Nov-18                  294.36
Dec-18                  271.51
Jan-19                  265.49
Feb-19                  256.51
Mar-19                   240.3
Apr-19                  257.25
May-19                  249.52
Jun-19                  226.07
Jul-19                  203.55
Aug-19                  223.86
Sep-19                   227.5
Oct-19                  233.38
Nov-19                  251.21
Dec-19                   263.9
Jan-20                  237.22
Feb-20                  241.78
Mar-20                  255.33
Apr-20                     277
YoY April                 7.68
MoM                       8.49
Lowest          Borno (117.19)
Highest       Bayelsa (462.22)
Name: 5, dtype: object
6 ItemLabels    Wheat flour: prepacked (golden penny 2kg)
Jan-17                                           626.53
Feb-17                                           621.39
Mar-17                                            623.1
Apr-17                                           627.33
May-17                                           646.18
Jun-17                                           632.09
Jul-17                                           630.47
Aug-17                                           647.29
Sep-17                                              627
Oct-17                                           641.41
Nov-17                                           649.19
Dec-17                                           639.24
Jan-18                                           655.15
Feb-18                                              646
Mar-18                                           657.64
Apr-18                                           649.92
May-18                                           659.51
Jun-18                                           660.13
Jul-18                                           657.58
Aug-18                                           661.06
Sep-18                                           651.87
Oct-18                                            656.8
Nov-18                                           659.65
Dec-18                                           662.89
Jan-19                                           665.12
Feb-19                                           664.78
Mar-19                                            663.9
Apr-19                                           668.76
May-19                                           668.37
Jun-19                                           674.83
Jul-19                                           667.97
Aug-19                                           663.26
Sep-19                                           664.02
Oct-19                                            675.3
Nov-19                                           673.48
Dec-19                                            676.2
Jan-20                                           672.79
Feb-20                                           668.01
Mar-20                                           674.14
Apr-20                                            692.6
YoY April                                          3.57
MoM                                                2.74
Lowest                                       Kogi (575)
Highest                                 Rivers (805.56)
Name: 6, dtype: object
7 ItemLabels        Yam tuber
Jan-17               210.58
Feb-17               215.55
Mar-17               255.86
Apr-17                250.3
May-17               279.15
Jun-17               292.06
Jul-17               294.12
Aug-17               343.39
Sep-17               259.51
Oct-17               223.63
Nov-17               212.27
Dec-17               211.61
Jan-18               226.51
Feb-18               230.85
Mar-18               254.51
Apr-18               279.61
May-18               291.33
Jun-18               285.84
Jul-18               280.83
Aug-18               292.97
Sep-18               280.28
Oct-18               252.21
Nov-18               239.15
Dec-18               212.65
Jan-19               211.21
Feb-19               206.49
Mar-19               200.88
Apr-19               222.36
May-19               216.03
Jun-19               182.15
Jul-19               170.85
Aug-19               190.04
Sep-19               190.23
Oct-19               179.75
Nov-19                203.2
Dec-19               206.82
Jan-20               193.04
Feb-20               189.53
Mar-20               206.12
Apr-20               230.09
YoY April              3.48
MoM                   11.63
Lowest         Yobe (102.6)
Highest       Osun (451.24)
Name: 7, dtype: object
8 ItemLabels    Agric eggs medium size
Jan-17                        512.99
Feb-17                        520.16
Mar-17                        507.69
Apr-17                        518.66
May-17                        522.71
Jun-17                        514.66
Jul-17                         498.5
Aug-17                        485.19
Sep-17                        487.51
Oct-17                        472.85
Nov-17                        463.11
Dec-17                        494.43
Jan-18                        437.13
Feb-18                        519.07
Mar-18                        527.32
Apr-18                        552.09
May-18                        548.66
Jun-18                        539.75
Jul-18                        471.75
Aug-18                        474.13
Sep-18                        472.73
Oct-18                         482.9
Nov-18                        477.76
Dec-18                        466.97
Jan-19                        469.86
Feb-19                        464.27
Mar-19                        459.81
Apr-19                        467.18
May-19                        464.87
Jun-19                        495.33
Jul-19                        468.31
Aug-19                        461.89
Sep-19                        456.81
Oct-19                        462.46
Nov-19                        463.91
Dec-19                         457.8
Jan-20                        454.17
Feb-20                        448.26
Mar-20                        461.15
Apr-20                        476.72
YoY April                       2.04
MoM                             3.38
Lowest                Gombe (400.77)
Highest              Rivers (587.42)
Name: 8, dtype: object
9 ItemLabels    Agric eggs(medium size price of one)
Jan-17                                       47.42
Feb-17                                        42.9
Mar-17                                       43.93
Apr-17                                       46.22
May-17                                       45.73
Jun-17                                       45.28
Jul-17                                       44.32
Aug-17                                       42.92
Sep-17                                       45.72
Oct-17                                       42.06
Nov-17                                       40.82
Dec-17                                       41.32
Jan-18                                       38.85
Feb-18                                       41.27
Mar-18                                       41.21
Apr-18                                       42.25
May-18                                       41.77
Jun-18                                       41.38
Jul-18                                       41.22
Aug-18                                       41.79
Sep-18                                       41.17
Oct-18                                       41.73
Nov-18                                        42.4
Dec-18                                       42.58
Jan-19                                       42.18
Feb-19                                       42.23
Mar-19                                       41.92
Apr-19                                       41.95
May-19                                       42.82
Jun-19                                       39.31
Jul-19                                       38.38
Aug-19                                       40.57
Sep-19                                        41.3
Oct-19                                       40.51
Nov-19                                       41.18
Dec-19                                       40.72
Jan-20                                       40.17
Feb-20                                       39.29
Mar-20                                        39.9
Apr-20                                       41.54
YoY April                                    -0.98
MoM                                           4.11
Lowest                               Gombe (35.15)
Highest                             Rivers (49.95)
Name: 9, dtype: object
10 ItemLabels    Beans brown,sold loose
Jan-17                         353.6
Feb-17                        337.11
Mar-17                        353.28
Apr-17                        357.19
May-17                        365.86
Jun-17                        374.26
Jul-17                        382.35
Aug-17                        370.25
Sep-17                        404.84
Oct-17                        382.58
Nov-17                        369.78
Dec-17                        361.97
Jan-18                        385.53
Feb-18                        387.48
Mar-18                        395.34
Apr-18                        395.19
May-18                        407.73
Jun-18                        418.78
Jul-18                        411.02
Aug-18                        410.16
Sep-18                        416.07
Oct-18                        411.05
Nov-18                        396.73
Dec-18                        386.78
Jan-19                        382.76
Feb-19                        373.91
Mar-19                        368.07
Apr-19                        372.84
May-19                        365.32
Jun-19                        342.82
Jul-19                        327.18
Aug-19                        307.27
Sep-19                        318.99
Oct-19                        308.93
Nov-19                         307.3
Dec-19                        299.48
Jan-20                        285.61
Feb-20                         276.3
Mar-20                        267.81
Apr-20                        277.05
YoY April                     -25.69
MoM                             3.45
Lowest                  Yobe (130.9)
Highest              Ebonyi (504.26)
Name: 10, dtype: object
11 ItemLabels    Beans:white black eye. sold loose
Jan-17                                   305.53
Feb-17                                   309.85
Mar-17                                   318.45
Apr-17                                   324.04
May-17                                   332.28

In [68]:
#cleaning data
ng.dropna()

,ItemLabels,Jan-17,Feb-17,Mar-17,Apr-17,May-17,Jun-17,Jul-17,Aug-17,Sep-17,...,Nov-19,Dec-19,Jan-20,Feb-20,Mar-20,Apr-20,YoY April,MoM,Lowest,Highest
0,Bread sliced 500g,302.87,299.75,297.51,296.63,307.70,320.58,314.47,304.20,310.62,...,299.59,304.06,302.45,303.06,304.60,316.55,6.27,3.92,Bauchi (238.57),Bayelsa (446.15)
1,"Gari white,sold loose",219.56,260.94,273.67,288.45,292.97,315.61,317.10,310.15,301.99,...,160.06,159.39,159.64,159.33,164.60,190.23,16.44,15.57,Ekiti (126.84),Bayelsa (325.48)
2,"Gari yellow,sold loose",255.83,250.45,302.05,320.92,326.83,354.55,350.46,345.82,335.94,...,181.32,183.26,182.19,186.35,192.41,211.83,16.02,10.09,Benue (146.57),Bayelsa (345.48)
3,Rice Medium Grained,312.08,352.69,377.99,332.81,350.36,348.23,344.40,313.45,339.47,...,378.50,381.68,381.42,373.16,368.36,394.56,24.74,7.11,Kogi (255),Bayelsa (580)
4,"Rice,imported high quality sold loose",402.01,410.58,418.71,388.46,410.55,415.84,409.20,384.35,398.01,...,445.45,459.90,453.24,444.04,438.66,471.84,31.97,7.56,Sokoto (353.33),Bayelsa (659.64)
5,Tomato,247.55,236.62,268.64,285.72,339.72,375.00,394.13,431.30,322.39,...,251.21,263.90,237.22,241.78,255.33,277.00,7.68,8.49,Borno (117.19),Bayelsa (462.22)
6,Wheat flour: prepacked (golden penny 2kg),626.53,621.39,623.10,627.33,646.18,632.09,630.47,647.29,627.00,...,673.48,676.20,672.79,668.01,674.14,692.60,3.57,2.74,Kogi (575),Rivers (805.56)
7,Yam tuber,210.58,215.55,255.86,250.30,279.15,292.06,294.12,343.39,259.51,...,203.20,206.82,193.04,189.53,206.12,230.09,3.48,11.63,Yobe (102.6),Osun (451.24)
8,Agric eggs medium size,512.99,520.16,507.69,518.66,522.71,514.66,498.50,485.19,487.51,...,463.91,457.80,454.17,448.26,461.15,476.72,2.04,3.38,Gombe (400.77),Rivers (587.42)
9,Agric eggs(medium size price of one),47.42,42.90,43.93,46.22,45.73,45.28,44.32,42.92,45.72,...,41.18,40.72,40.17,39.29,39.90,41.54,-0.98,4.11,Gombe (35.15),Rivers (49.95)
10,"Beans brown,sold loose",353.60,337.11,353.28,357.19,365.86,374.26,382.35,370.25,404.84,...,307.30,299.48,285.61,276.30,267.81,277.05,-25.69,3.45,Yobe (130.9),Ebonyi (504.26)
11,Beans:white black eye. sold loose,305.53,309.85,318.45,324.04,332.28,339.64,343.96,335.71,358.13,...,284.65,281.60,268.80,255.25,241.74,250.33,-24.02,3.55,Yobe (149.49),Ebonyi (460.94)
12,Beef Bone in,1001.24,995.65,1010.29,1035.45,1123.65,1129.02,1128.94,1151.38,1078.49,...,1026.24,1045.86,1031.53,1035.38,1025.48,1047.12,2.13,2.11,Osun (786.22),Cross River (1403.85)
13,"Beef,boneless",1249.48,1270.67,1281.71,1323.10,1378.91,1393.42,1376.91,1276.85,1324.93,...,1293.00,1292.52,1289.80,1279.60,1276.10,1307.68,2.88,2.47,Adamawa (1092.02),Enugu (1514.82)
14,Bread unsliced 500g,270.25,264.86,262.33,277.69,282.26,286.78,285.55,258.70,286.33,...,280.51,277.79,276.26,275.20,278.79,288.45,6.25,3.46,Bauchi (226),Bayelsa (425)
15,Broken Rice (Ofada),377.41,392.04,421.54,425.53,460.10,472.29,473.40,415.34,431.59,...,396.86,406.94,409.31,404.32,390.54,408.05,7.06,4.48,Cross River (263.22),Lagos (644.14)
16,Catfish :dried,2204.12,2150.18,2189.55,2189.10,2213.66,2255.24,2215.25,2176.82,2159.00,...,1723.23,1732.45,1720.55,1713.30,1711.32,1724.52,-2.22,0.77,Zamfara (1195),Imo (2699.05)
17,Catfish (obokun) fresh,899.58,885.13,884.15,886.65,900.73,916.55,910.57,921.17,894.52,...,1027.76,1043.41,1025.13,1022.84,1027.30,1048.90,-3.06,2.10,Yobe (800.1),Abia (1400)
18,Catfish Smoked,817.09,825.35,834.26,837.09,845.91,848.41,853.18,852.93,839.49,...,1501.28,1507.39,1502.48,1496.07,1501.97,1524.80,-1.51,1.52,Sokoto (1242),Abuja (1840)
19,Chicken Feet,765.28,785.42,907.51,768.11,819.59,832.79,832.66,834.74,817.19,...,686.71,699.06,685.98,684.50,691.70,711.61,-4.65,2.88,Bauchi (350),Bayelsa (1280.98)
20,Chicken Wings,919.09,963.46,980.88,886.58,925.55,952.18,958.05,946.93,979.32,...,893.00,915.62,909.31,922.52,920.52,935.60,-1.31,1.64,Taraba (529.42),Edo (1454.17)
21,Dried Fish Sardine,959.11,935.51,958.67,972.73,991.64,989.49,968.76,972.65,947.60,...,1423.23,1444.94,1454.59,1440.71,1432.95,1447.58,2.35,1.02,Katsina (1000),Anambra (1800)
22,Evaporated tinned milk carnation 170g,136.29,140.53,143.56,151.47,157.95,162.80,162.72,158.85,174.36,...,157.21,157.89,157.11,150.54,153.37,160.98,-0.43,4.96,Nassarawa (140.88),Ekiti (203.33)
23,"Evaporated tinned milk(peak), 170g",157.75,166.14,177.05,197.15,198.42,194.67,195.94,190.53,206.00,...,183.56,184.80,185.63,183.81,183.12,190.17,1.06,3.85,Kano (162.33),Lagos (204.25)
24,Frozen chicken,1419.75,1428.95,1555.51,1606.63,1605.97,1645.29,1623.84,1529.25,1570.26,...,2008.39,1995.58,1983.14,1948.59,1941.04,1958.10,16.48,0.88,Kano (1450),Plateau (3057.14)
25,"Groundnut oil: 1 bottle, specify bottle",477.86,482.94,494.10,494.24,500.19,503.28,505.12,508.33,477.97,...,580.03,580.45,571.88,572.36,583.22,601.03,3.89,3.05,Kogi (440),Cross River (860)
26,Iced Sardine,1879.96,1915.68,1902.15,1927.97,1919.64,1916.19,1915.25,1904.67,1878.46,...,956.79,969.60,964.40,961.21,960.69,987.10,4.85,2.75,Osun (716.38),Bayelsa (1238.83)
27,Irish potato,300.95,307.29,311.81,318.88,315.86,319.30,311.40,310.48,307.46,...,289.23,304.46,281.09,286.21,301.24,309.85,6.96,2.86,Niger (151.05),Edo (496.38)
28,Mackerel : frozen,759.01,764.62,774.89,778.15,785.37,794.64,795.82,797.77,785.57,...,951.67,953.29,946.05,932.21,928.27,953.14,-0.51,2.68,Ekiti (785.82),Abuja (1200)
29,Maize grain white sold loose,167.11,172.86,174.03,182.94,188.90,190.33,191.33,192.44,168.12,...,149.63,151.88,148.86,150.15,150.78,165.83,9.32,9.98,Borno (83.31),Bayelsa (307.29)
30,Maize grain yellow sold loose,168.77,174.72,178.79,185.61,190.59,191.36,193.02,193.43,168.19,...,151.65,153.00,149.62,151.53,150.97,166.42,6.75,10.23,Borno (79.77),Bayelsa (353.32)
31,Mudfish : dried,1812.03,1955.10,2084.81,2319.91,2388.05,2416.28,2395.79,2161.70,2204.04,...,1756.42,1774.96,1758.76,1764.13,1742.72,1762.88,-3.49,1.16,Jigawa (1286.25),Abia (2403.17)
32,Mudfish (aro) fresh,994.37,998.71,1079.16,1008.95,1047.28,1071.13,1080.33,998.57,1069.92,...,1002.74,1010.99,1000.41,992.95,991.44,1004.18,-3.25,1.29,Adamawa (737.24),Enugu (1544.07)
33,Onion bulb,258.92,241.44,246.95,205.60,203.56,214.79,213.14,236.66,238.29,...,226.06,240.55,225.83,231.60,236.36,227.59,-2.03,-3.71,Katsina (111.11),Akwa Ibom (377.2)
34,"Palm oil: 1 bottle,specify bottle",420.62,434.81,442.04,452.42,458.24,471.28,478.75,492.90,439.88,...,466.93,469.43,457.59,457.31,451.37,464.08,0.66,2.82,Cross River (346.67),Kaduna (549.33)
35,Plantain(ripe),234.25,234.28,236.65,240.71,241.48,249.71,251.27,254.02,231.70,...,218.01,213.04,206.17,207.82,220.91,236.49,3.57,7.05,Cross River (153.89),Plateau (330.26)
36,Plantain(unripe),212.49,214.41,215.80,221.79,224.65,228.46,223.47,226.26,215.96,...,203.49,204.30,197.06,201.83,218.05,230.20,4.20,5.57,Gombe (164.32),Plateau (343.02)
37,Rice agric sold loose,324.01,355.41,360.89,324.76,347.73,352.09,354.08,349.64,351.09,...,384.04,390.18,382.21,377.69,369.89,393.34,23.08,6.34,Kebbi (267.17),Bayelsa (591.17)
38,Rice local sold loose,286.19,306.29,308.87,299.30,323.82,325.51,323.25,320.19,316.40,...,344.01,345.94,338.58,334.11,313.10,342.49,21.12,9.39,Sokoto (232.65),Bayelsa (530.88)
39,Sweet potato,129.43,127.23,132.94,132.43,130.28,135.77,137.96,138.56,139.00,...,146.58,147.46,141.23,141.34,149.46,153.89,8.67,2.97,Borno (72.22),Kebbi (260.54)
40,Tilapia fish (epiya) fresh,792.18,795.27,798.07,800.77,805.21,817.62,823.34,820.29,795.64,...,859.55,884.07,870.06,863.29,854.86,870.49,-2.64,1.83,Taraba (549.18),Bayelsa (1283)
41,Titus:frozen,884.82,942.23,964.63,935.00,969.64,1012.18,1014.54,998.01,973.99,...,975.39,981.21,962.96,948.14,960.47,986.88,1.23,2.75,Osun (723.08),Delta (1204.75)
42,"Vegetable oil:1 bottle,specify bottle",495.29,507.36,513.42,525.72,524.77,546.29,552.91,559.01,505.51,...,512.53,516.29,515.48,520.95,530.85,551.92,10.15,3.97,Kwara (447.5),Rivers (698.04)

In [75]:
#getting properties of our data
ng.shape
ng.info()
ng.describe()
ng.index

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 47 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ItemLabels    43 non-null     object
 1   Jan-17        43 non-null     float64
 2   Feb-17        43 non-null     float64
 3   Mar-17        43 non-null     float64
 4   Apr-17        43 non-null     float64
 5   May-17        43 non-null     float64
 6   Jun-17        43 non-null     float64
 7   Jul-17        43 non-null     float64
 8   Aug-17        43 non-null     float64
 9   Sep-17        43 non-null     float64
 10  Oct-17        43 non-null     float64
 11  Nov-17        43 non-null     float64
 12  Dec-17        43 non-null     float64
 13  Jan-18        43 non-null     float64
 14  Feb-18        43 non-null     float64
 15  Mar-18        43 non-null     float64
 16  Apr-18        43 non-null     float64
 17  May-18        43 non-null     float64
 18  Jun-18        43 non-null     float64
 19  Jul-18        43 non-null     float64
 20  Aug-18        43 non-null     float64
 21  Sep-18        43 non-null     float64
 22  Oct-18        43 non-null     float64
 23  Nov-18        43 non-null     float64
 24  Dec-18        43 non-null     float64
 25  Jan-19        43 non-null     float64
 26  Feb-19        43 non-null     float64
 27  Mar-19        43 non-null     float64
 28  Apr-19        43 non-null     float64
 29  May-19        43 non-null     float64
 30  Jun-19        43 non-null     float64
 31  Jul-19        43 non-null     float64
 32  Aug-19        43 non-null     float64
 33  Sep-19        43 non-null     float64
 34  Oct-19        43 non-null     float64
 35  Nov-19        43 non-null     float64
 36  Dec-19        43 non-null     float64
 37  Jan-20        43 non-null     float64
 38  Feb-20        43 non-null     float64
 39  Mar-20        43 non-null     float64
 40  Apr-20        43 non-null     float64
 41  YoY April     43 non-null     float64
 42  MoM           43 non-null     float64
 43  Lowest        43 non-null     object
 44  Highest       43 non-null     object
 45  higher price  43 non-null     object
 46  lower price   43 non-null     object
dtypes: float64(42), object(5)
memory usage: 15.9+ KB

RangeIndex(start=0, stop=43, step=1)

In [76]:
#obtaining the 2nd row of the data frame
ng.iloc[1]

ItemLabels      Gari white,sold loose
Jan-17                         219.56
Feb-17                         260.94
Mar-17                         273.67
Apr-17                         288.45
May-17                         292.97
Jun-17                         315.61
Jul-17                          317.1
Aug-17                         310.15
Sep-17                         301.99
Oct-17                          268.1
Nov-17                         251.91
Dec-17                         199.68
Jan-18                         229.26
Feb-18                         210.21
Mar-18                         209.12
Apr-18                         208.21
May-18                         216.01
Jun-18                         216.72
Jul-18                         200.67
Aug-18                         198.82
Sep-18                         195.86
Oct-18                         188.39
Nov-18                         183.59
Dec-18                         166.64
Jan-19                          165.8
Feb-19                         166.61
Mar-19                         163.51
Apr-19                         163.37
May-19                         161.55
Jun-19                         145.31
Jul-19                         151.73
Aug-19                          154.1
Sep-19                         154.55
Oct-19                         162.42
Nov-19                         160.06
Dec-19                         159.39
Jan-20                         159.64
Feb-20                         159.33
Mar-20                          164.6
Apr-20                         190.23
YoY April                       16.44
MoM                             15.57
Lowest                         Ekiti
Highest                      Bayelsa
higher price                  325.48)
lower price                   126.84)
Name: 1, dtype: object

In [77]:
#obtaining a list of foods with prices greater 
#than 1600 Naira between May amd December 2019

ng[(ng["May-19"]>1600) & (ng["Dec-19"]>1600)]

,ItemLabels,Jan-17,Feb-17,Mar-17,Apr-17,May-17,Jun-17,Jul-17,Aug-17,Sep-17,...,Jan-20,Feb-20,Mar-20,Apr-20,YoY April,MoM,Lowest,Highest,higher price,lower price
16,Catfish :dried,2204.12,2150.18,2189.55,2189.10,2213.66,2255.24,2215.25,2176.82,2159.00,...,1720.55,1713.30,1711.32,1724.52,-2.22,0.77,Zamfara,Imo,2699.05),1195)
24,Frozen chicken,1419.75,1428.95,1555.51,1606.63,1605.97,1645.29,1623.84,1529.25,1570.26,...,1983.14,1948.59,1941.04,1958.10,16.48,0.88,Kano,Plateau,3057.14),1450)
31,Mudfish : dried,1812.03,1955.10,2084.81,2319.91,2388.05,2416.28,2395.79,2161.70,2204.04,...,1758.76,1764.13,1742.72,1762.88,-3.49,1.16,Jigawa,Abia,2403.17),1286.25)

In [ ]:
#splitting highest and lowest columns using delimiters
ng[["Highest","higher price"]] = ng["Highest"].str.split("()",expand=True)
ng[["Lowest","lower price"]] = ng["Lowest"].str.split("()",expand=True)
ng

In [78]:
ng

,ItemLabels,Jan-17,Feb-17,Mar-17,Apr-17,May-17,Jun-17,Jul-17,Aug-17,Sep-17,...,Jan-20,Feb-20,Mar-20,Apr-20,YoY April,MoM,Lowest,Highest,higher price,lower price
0,Bread sliced 500g,302.87,299.75,297.51,296.63,307.70,320.58,314.47,304.20,310.62,...,302.45,303.06,304.60,316.55,6.27,3.92,Bauchi,Bayelsa,446.15),238.57)
1,"Gari white,sold loose",219.56,260.94,273.67,288.45,292.97,315.61,317.10,310.15,301.99,...,159.64,159.33,164.60,190.23,16.44,15.57,Ekiti,Bayelsa,325.48),126.84)
2,"Gari yellow,sold loose",255.83,250.45,302.05,320.92,326.83,354.55,350.46,345.82,335.94,...,182.19,186.35,192.41,211.83,16.02,10.09,Benue,Bayelsa,345.48),146.57)
3,Rice Medium Grained,312.08,352.69,377.99,332.81,350.36,348.23,344.40,313.45,339.47,...,381.42,373.16,368.36,394.56,24.74,7.11,Kogi,Bayelsa,580),255)
4,"Rice,imported high quality sold loose",402.01,410.58,418.71,388.46,410.55,415.84,409.20,384.35,398.01,...,453.24,444.04,438.66,471.84,31.97,7.56,Sokoto,Bayelsa,659.64),353.33)
5,Tomato,247.55,236.62,268.64,285.72,339.72,375.00,394.13,431.30,322.39,...,237.22,241.78,255.33,277.00,7.68,8.49,Borno,Bayelsa,462.22),117.19)
6,Wheat flour: prepacked (golden penny 2kg),626.53,621.39,623.10,627.33,646.18,632.09,630.47,647.29,627.00,...,672.79,668.01,674.14,692.60,3.57,2.74,Kogi,Rivers,805.56),575)
7,Yam tuber,210.58,215.55,255.86,250.30,279.15,292.06,294.12,343.39,259.51,...,193.04,189.53,206.12,230.09,3.48,11.63,Yobe,Osun,451.24),102.6)
8,Agric eggs medium size,512.99,520.16,507.69,518.66,522.71,514.66,498.50,485.19,487.51,...,454.17,448.26,461.15,476.72,2.04,3.38,Gombe,Rivers,587.42),400.77)
9,Agric eggs(medium size price of one),47.42,42.90,43.93,46.22,45.73,45.28,44.32,42.92,45.72,...,40.17,39.29,39.90,41.54,-0.98,4.11,Gombe,Rivers,49.95),35.15)
10,"Beans brown,sold loose",353.60,337.11,353.28,357.19,365.86,374.26,382.35,370.25,404.84,...,285.61,276.30,267.81,277.05,-25.69,3.45,Yobe,Ebonyi,504.26),130.9)
11,Beans:white black eye. sold loose,305.53,309.85,318.45,324.04,332.28,339.64,343.96,335.71,358.13,...,268.80,255.25,241.74,250.33,-24.02,3.55,Yobe,Ebonyi,460.94),149.49)
12,Beef Bone in,1001.24,995.65,1010.29,1035.45,1123.65,1129.02,1128.94,1151.38,1078.49,...,1031.53,1035.38,1025.48,1047.12,2.13,2.11,Osun,Cross River,1403.85),786.22)
13,"Beef,boneless",1249.48,1270.67,1281.71,1323.10,1378.91,1393.42,1376.91,1276.85,1324.93,...,1289.80,1279.60,1276.10,1307.68,2.88,2.47,Adamawa,Enugu,1514.82),1092.02)
14,Bread unsliced 500g,270.25,264.86,262.33,277.69,282.26,286.78,285.55,258.70,286.33,...,276.26,275.20,278.79,288.45,6.25,3.46,Bauchi,Bayelsa,425),226)
15,Broken Rice (Ofada),377.41,392.04,421.54,425.53,460.10,472.29,473.40,415.34,431.59,...,409.31,404.32,390.54,408.05,7.06,4.48,Cross River,Lagos,644.14),263.22)
16,Catfish :dried,2204.12,2150.18,2189.55,2189.10,2213.66,2255.24,2215.25,2176.82,2159.00,...,1720.55,1713.30,1711.32,1724.52,-2.22,0.77,Zamfara,Imo,2699.05),1195)
17,Catfish (obokun) fresh,899.58,885.13,884.15,886.65,900.73,916.55,910.57,921.17,894.52,...,1025.13,1022.84,1027.30,1048.90,-3.06,2.10,Yobe,Abia,1400),800.1)
18,Catfish Smoked,817.09,825.35,834.26,837.09,845.91,848.41,853.18,852.93,839.49,...,1502.48,1496.07,1501.97,1524.80,-1.51,1.52,Sokoto,Abuja,1840),1242)
19,Chicken Feet,765.28,785.42,907.51,768.11,819.59,832.79,832.66,834.74,817.19,...,685.98,684.50,691.70,711.61,-4.65,2.88,Bauchi,Bayelsa,1280.98),350)
20,Chicken Wings,919.09,963.46,980.88,886.58,925.55,952.18,958.05,946.93,979.32,...,909.31,922.52,920.52,935.60,-1.31,1.64,Taraba,Edo,1454.17),529.42)
21,Dried Fish Sardine,959.11,935.51,958.67,972.73,991.64,989.49,968.76,972.65,947.60,...,1454.59,1440.71,1432.95,1447.58,2.35,1.02,Katsina,Anambra,1800),1000)
22,Evaporated tinned milk carnation 170g,136.29,140.53,143.56,151.47,157.95,162.80,162.72,158.85,174.36,...,157.11,150.54,153.37,160.98,-0.43,4.96,Nassarawa,Ekiti,203.33),140.88)
23,"Evaporated tinned milk(peak), 170g",157.75,166.14,177.05,197.15,198.42,194.67,195.94,190.53,206.00,...,185.63,183.81,183.12,190.17,1.06,3.85,Kano,Lagos,204.25),162.33)
24,Frozen chicken,1419.75,1428.95,1555.51,1606.63,1605.97,1645.29,1623.84,1529.25,1570.26,...,1983.14,1948.59,1941.04,1958.10,16.48,0.88,Kano,Plateau,3057.14),1450)
25,"Groundnut oil: 1 bottle, specify bottle",477.86,482.94,494.10,494.24,500.19,503.28,505.12,508.33,477.97,...,571.88,572.36,583.22,601.03,3.89,3.05,Kogi,Cross River,860),440)
26,Iced Sardine,1879.96,1915.68,1902.15,1927.97,1919.64,1916.19,1915.25,1904.67,1878.46,...,964.40,961.21,960.69,987.10,4.85,2.75,Osun,Bayelsa,1238.83),716.38)
27,Irish potato,300.95,307.29,311.81,318.88,315.86,319.30,311.40,310.48,307.46,...,281.09,286.21,301.24,309.85,6.96,2.86,Niger,Edo,496.38),151.05)
28,Mackerel : frozen,759.01,764.62,774.89,778.15,785.37,794.64,795.82,797.77,785.57,...,946.05,932.21,928.27,953.14,-0.51,2.68,Ekiti,Abuja,1200),785.82)
29,Maize grain white sold loose,167.11,172.86,174.03,182.94,188.90,190.33,191.33,192.44,168.12,...,148.86,150.15,150.78,165.83,9.32,9.98,Borno,Bayelsa,307.29),83.31)
30,Maize grain yellow sold loose,168.77,174.72,178.79,185.61,190.59,191.36,193.02,193.43,168.19,...,149.62,151.53,150.97,166.42,6.75,10.23,Borno,Bayelsa,353.32),79.77)
31,Mudfish : dried,1812.03,1955.10,2084.81,2319.91,2388.05,2416.28,2395.79,2161.70,2204.04,...,1758.76,1764.13,1742.72,1762.88,-3.49,1.16,Jigawa,Abia,2403.17),1286.25)
32,Mudfish (aro) fresh,994.37,998.71,1079.16,1008.95,1047.28,1071.13,1080.33,998.57,1069.92,...,1000.41,992.95,991.44,1004.18,-3.25,1.29,Adamawa,Enugu,1544.07),737.24)
33,Onion bulb,258.92,241.44,246.95,205.60,203.56,214.79,213.14,236.66,238.29,...,225.83,231.60,236.36,227.59,-2.03,-3.71,Katsina,Akwa Ibom,377.2),111.11)
34,"Palm oil: 1 bottle,specify bottle",420.62,434.81,442.04,452.42,458.24,471.28,478.75,492.90,439.88,...,457.59,457.31,451.37,464.08,0.66,2.82,Cross River,Kaduna,549.33),346.67)
35,Plantain(ripe),234.25,234.28,236.65,240.71,241.48,249.71,251.27,254.02,231.70,...,206.17,207.82,220.91,236.49,3.57,7.05,Cross River,Plateau,330.26),153.89)
36,Plantain(unripe),212.49,214.41,215.80,221.79,224.65,228.46,223.47,226.26,215.96,...,197.06,201.83,218.05,230.20,4.20,5.57,Gombe,Plateau,343.02),164.32)
37,Rice agric sold loose,324.01,355.41,360.89,324.76,347.73,352.09,354.08,349.64,351.09,...,382.21,377.69,369.89,393.34,23.08,6.34,Kebbi,Bayelsa,591.17),267.17)
38,Rice local sold loose,286.19,306.29,308.87,299.30,323.82,325.51,323.25,320.19,316.40,...,338.58,334.11,313.10,342.49,21.12,9.39,Sokoto,Bayelsa,530.88),232.65)
39,Sweet potato,129.43,127.23,132.94,132.43,130.28,135.77,137.96,138.56,139.00,...,141.23,141.34,149.46,153.89,8.67,2.97,Borno,Kebbi,260.54),72.22)
40,Tilapia fish (epiya) fresh,792.18,795.27,798.07,800.77,805.21,817.62,823.34,820.29,795.64,...,870.06,863.29,854.86,870.49,-2.64,1.83,Taraba,Bayelsa,1283),549.18)
41,Titus:frozen,884.82,942.23,964.63,935.00,969.64,1012.18,1014.54,998.01,973.99,...,962.96,948.14,960.47,986.88,1.23,2.75,Osun,Delta,1204.75),723.08)
42,"Vegetable oil:1 bottle,specify bottle",495.29,507.36,513.42,525.72,524.77,546.29,552.91,559.01,505.51,...,515.48,520.95,530.85,551.92,10.15,3.97,Kwara,Rivers,698.04),447.5)

In [79]:
#splitting highest and lowest columns using delimiters
ng[["Highest","higher price"]] = ng["Highest"].str.split("(:/)",expand=True)
ng[["Lowest","lower price"]] = ng["Lowest"].str.split("(:/)",expand=True)
ng

ValueError: Columns must be same length as key